version: '3.4'

services:
  creditline-api:
    container_name: creditline-api
    build: ./
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - creditline-db

  creditline-db:
    container_name: creditline-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe!
      POSTGRES_DB: creditline
    volumes:
      - identity-postgres-data:/var/lib/postgres

volumes:
  identity-postgres-data:
